### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by huglester** [websemantics/timetable-module#2]
Hello,

I do get this error:

``` php
ErrorException in metadata.twig line 26:
An exception has been thrown during the rendering of a template ("variable @primary is undefined in file anonymous-file-0.less in anonymous-file-0.less") in "theme::partials/metadata" at line 26.
```

**Comment by websemantics** [comment]
Thanks @huglester, .. I've built that on a different theme, and used other variables,

I realized I wanted to change module name and stream used, so I had to recreate it. Called it Calendar Module, https://github.com/websemantics/calendar-module

Also thanks for the pull request, I made the changes in the new repo, ... will delete this repo in few days, 

Feel free to create any issues you have with the Calendar Module, it is far from complete,
